"use client";

import React, { useActionState, useState } from "react";
import { verifyMfaAction } from "@/actions/auth";
import { Card, CardHeader, CardTitle, CardContent } from "@/components/ui/card";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { ShieldCheck, AlertCircle, Laptop } from "lucide-react";

export function MfaVerifyForm({
  email,
  isEnrollment = false,
}: {
  email: string;
  isEnrollment?: boolean;
}) {
  const [state, formAction, isPending] = useActionState(verifyMfaAction, null);
  const [code, setCode] = useState("");
  const [trustDevice, setTrustDevice] = useState(true);

  return (
    <Card className="p-6 sm:p-8 shadow-2xl border-white/10 bg-white">
      <CardHeader className="p-0 pb-6 text-center">
        <CardTitle className="font-serif text-2xl font-bold text-cambria-navy">
          {isEnrollment ? "Complete Authenticator Setup" : "Enter 6-Digit TOTP Code"}
        </CardTitle>
        <p className="text-xs text-slate-500 pt-1">
          {isEnrollment
            ? "Enter the 6-digit confirmation code generated by your authenticator app to complete enrollment."
            : (
              <>
                Enter the dynamic time-based passcode from your authenticator device for{" "}
                <span className="font-semibold text-slate-700">{email}</span>.
              </>
            )}
        </p>
      </CardHeader>

      <CardContent className="p-0">
        {state?.error && (
          <div className="mb-4 p-3 bg-rose-50 border border-rose-200 rounded-[4px] text-xs text-rose-800 flex items-start gap-2">
            <AlertCircle className="w-4 h-4 text-rose-700 shrink-0 mt-0.5" />
            <div className="space-y-1">
              <span className="font-semibold block">{state.error}</span>
              <span className="text-[11px] text-rose-700 block">
                Make sure your phone&apos;s Date &amp; Time is set to <strong>Automatic Network Time</strong>, or scan the QR code above again.
              </span>
            </div>
          </div>
        )}

        <form action={formAction} className="space-y-5">
          <div className="space-y-1.5">
            <label className="text-xs font-semibold text-slate-700 block text-center">
              Security Passcode (6 Digits)
            </label>
            <Input
              name="code"
              type="text"
              inputMode="numeric"
              pattern="[0-9]{6}"
              maxLength={6}
              required
              autoFocus
              value={code}
              onChange={(e) => setCode(e.target.value.replace(/\D/g, ""))}
              placeholder="000000"
              className="rounded-[4px] border-slate-300 text-center tracking-[0.5em] font-mono text-2xl font-bold py-3.5 h-12"
            />
          </div>

          {/* Trust This Device for 30 Days */}
          <div className="p-3 bg-slate-50 border border-slate-200 rounded-[4px] flex items-start gap-3">
            <input
              type="checkbox"
              id="trustDevice"
              name="trustDevice"
              checked={trustDevice}
              onChange={(e) => setTrustDevice(e.target.checked)}
              className="mt-0.5 w-4 h-4 text-cambria-navy rounded border-slate-300 focus:ring-cambria-navy cursor-pointer accent-[#020B5A]"
            />
            <label htmlFor="trustDevice" className="text-xs text-slate-700 cursor-pointer select-none space-y-0.5">
              <span className="font-semibold text-slate-800 flex items-center gap-1.5">
                <Laptop className="w-3.5 h-3.5 text-cambria-academic" />
                Trust this device for 30 days
              </span>
              <span className="text-[11px] text-slate-500 block leading-tight">
                Skip two-factor verification on this browser for the next 30 days. Only enable on trusted personal work devices.
              </span>
            </label>
          </div>

          <div className="pt-1">
            <Button
              type="submit"
              disabled={isPending || code.length !== 6}
              className="w-full bg-cambria-navy hover:bg-cambria-academic text-white font-semibold py-2.5 rounded-[4px] gap-2 h-11"
            >
              <ShieldCheck className="w-4 h-4" />
              {isPending
                ? "Validating Passcode..."
                : isEnrollment
                ? "Verify Code & Complete Setup"
                : "Verify & Authorize Session"}
            </Button>
          </div>
        </form>
      </CardContent>
    </Card>
  );
}
