import { TemplateField, TemplateKind } from "@/types/database";

export interface DimensionPreset {
  label: string;
  width: number;
  height: number;
  kind: TemplateKind;
}

export const DIMENSION_PRESETS: DimensionPreset[] = [
  {
    label: "Certificate — Landscape Master (2000 × 1414 px)",
    width: 2000,
    height: 1414,
    kind: "certificate",
  },
  {
    label: "Certificate — Portrait Master (1414 × 2000 px)",
    width: 1414,
    height: 2000,
    kind: "certificate",
  },
  {
    label: "Student ID Card — CR80 Master (1013 × 638 px)",
    width: 1013,
    height: 638,
    kind: "student_card",
  },
  {
    label: "Certificate — A4 Landscape Legacy (1600 × 1131 px)",
    width: 1600,
    height: 1131,
    kind: "certificate",
  },
  {
    label: "Certificate — A4 Portrait Legacy (1131 × 1600 px)",
    width: 1131,
    height: 1600,
    kind: "certificate",
  },
  {
    label: "Student ID Card — CR80 Legacy (900 × 600 px)",
    width: 900,
    height: 600,
    kind: "student_card",
  },
];

export interface FieldPreset {
  label: string;
  labelAr: string;
  icon: string;
  field: Omit<TemplateField, "id">;
}

export const AVAILABLE_FIELD_PRESETS: FieldPreset[] = [
  {
    label: "Student Name (English)",
    labelAr: "اسم الطالب (إنجليزي)",
    icon: "GraduationCap",
    field: {
      type: "text",
      contentKey: "student_name_en",
      x: 200,
      y: 400,
      w: 1200,
      h: 60,
      font: "Cormorant Garamond",
      size: 42,
      weight: 700,
      color: "#020B5A",
      align: "center",
      direction: "ltr",
      label: "Student Name (EN)",
    },
  },
  {
    label: "Student Name (Arabic)",
    labelAr: "اسم الطالب (عربي)",
    icon: "Award",
    field: {
      type: "text",
      contentKey: "student_name_ar",
      x: 200,
      y: 470,
      w: 1200,
      h: 55,
      font: "Cairo",
      size: 32,
      weight: 700,
      color: "#020B5A",
      align: "center",
      direction: "rtl",
      label: "اسم الطالب (AR)",
    },
  },
  {
    label: "Program Name (English)",
    labelAr: "اسم البرنامج (إنجليزي)",
    icon: "BookOpen",
    field: {
      type: "text",
      contentKey: "program_name_en",
      x: 200,
      y: 590,
      w: 1200,
      h: 50,
      font: "Cormorant Garamond",
      size: 34,
      weight: 600,
      color: "#07133F",
      align: "center",
      direction: "ltr",
      label: "Program Name (EN)",
    },
  },
  {
    label: "Program Name (Arabic)",
    labelAr: "اسم البرنامج (عربي)",
    icon: "BookOpen",
    field: {
      type: "text",
      contentKey: "program_name_ar",
      x: 200,
      y: 650,
      w: 1200,
      h: 45,
      font: "Cairo",
      size: 26,
      weight: 600,
      color: "#243A8F",
      align: "center",
      direction: "rtl",
      label: "اسم البرنامج (AR)",
    },
  },
  {
    label: "Credential ID / Number",
    labelAr: "رقم الاعتماد / الشهادة",
    icon: "Hash",
    field: {
      type: "text",
      contentKey: "credential_number",
      x: 80,
      y: 1040,
      w: 400,
      h: 30,
      font: "Inter",
      size: 13,
      weight: 600,
      color: "#020B5A",
      align: "left",
      direction: "ltr",
      label: "Credential Number",
    },
  },
  {
    label: "Student ID Number",
    labelAr: "الرقم الجامعي للطالب",
    icon: "UserCheck",
    field: {
      type: "text",
      contentKey: "student_id_number",
      x: 80,
      y: 1070,
      w: 400,
      h: 30,
      font: "Inter",
      size: 12,
      weight: 500,
      color: "#64748B",
      align: "left",
      direction: "ltr",
      label: "Student ID",
    },
  },
  {
    label: "Date of Issue",
    labelAr: "تاريخ الإصدار",
    icon: "Calendar",
    field: {
      type: "text",
      contentKey: "issue_date",
      x: 80,
      y: 1010,
      w: 300,
      h: 25,
      font: "Inter",
      size: 12,
      weight: 500,
      color: "#64748B",
      align: "left",
      direction: "ltr",
      label: "Issue Date",
    },
  },
  {
    label: "Date of Expiry",
    labelAr: "تاريخ الانتهاء",
    icon: "Clock",
    field: {
      type: "text",
      contentKey: "expiry_date",
      x: 80,
      y: 1035,
      w: 300,
      h: 25,
      font: "Inter",
      size: 12,
      weight: 500,
      color: "#64748B",
      align: "left",
      direction: "ltr",
      label: "Expiry Date",
    },
  },
  {
    label: "Verification QR Code",
    labelAr: "رمز التحقق السريع QR",
    icon: "QrCode",
    field: {
      type: "qr",
      contentKey: "verification_url",
      x: 1380,
      y: 920,
      w: 140,
      h: 140,
      borderRadius: 4,
      label: "Verification QR Code",
    },
  },
  {
    label: "Student Photo / Avatar",
    labelAr: "صورة الطالب الشخصية",
    icon: "Camera",
    field: {
      type: "image",
      contentKey: "student_photo",
      x: 235,
      y: 120,
      w: 130,
      h: 160,
      borderRadius: 6,
      label: "Student Photo",
    },
  },
  {
    label: "College Official Seal",
    labelAr: "ختم الكلية الرسمي",
    icon: "Shield",
    field: {
      type: "image",
      contentKey: "college_seal",
      x: 740,
      y: 900,
      w: 120,
      h: 120,
      label: "College Seal",
    },
  },
  {
    label: "National ID (Masked)",
    labelAr: "الرقم القومي (محمي)",
    icon: "Fingerprint",
    field: {
      type: "text",
      contentKey: "student_national_id",
      x: 495,
      y: 338,
      w: 480,
      h: 38,
      font: "Montserrat",
      size: 26,
      weight: 600,
      color: "#07133F",
      align: "left",
      direction: "ltr",
      staticPrefix: ": ",
      label: "National ID",
    },
  },
  {
    label: "Country / Nationality",
    labelAr: "الدولة / الجنسية",
    icon: "Globe",
    field: {
      type: "text",
      contentKey: "student_country",
      x: 495,
      y: 396,
      w: 480,
      h: 38,
      font: "Montserrat",
      size: 26,
      weight: 600,
      color: "#07133F",
      align: "left",
      direction: "ltr",
      staticPrefix: ": ",
      label: "Country",
    },
  },
  {
    label: "Specialization",
    labelAr: "التخصص الأكاديمي",
    icon: "Briefcase",
    field: {
      type: "text",
      contentKey: "specialization",
      x: 495,
      y: 512,
      w: 480,
      h: 38,
      font: "Montserrat",
      size: 26,
      weight: 600,
      color: "#07133F",
      align: "left",
      direction: "ltr",
      staticPrefix: ": ",
      label: "Specialization",
    },
  },
  {
    label: "Academic Grade",
    labelAr: "التقدير الأكاديمي",
    icon: "Star",
    field: {
      type: "text",
      contentKey: "grade",
      x: 420,
      y: 960,
      w: 600,
      h: 35,
      font: "Montserrat",
      size: 22,
      weight: 600,
      color: "#0F172A",
      align: "left",
      direction: "ltr",
      staticPrefix: "Grade: ",
      label: "Grade",
    },
  },
  {
    label: "Custom Static Text",
    labelAr: "نص مخصص / لقب / توقيع",
    icon: "Type",
    field: {
      type: "text",
      staticText: "CAMBRIA INTERNATIONAL COLLEGE",
      x: 200,
      y: 130,
      w: 1200,
      h: 40,
      font: "Inter",
      size: 18,
      weight: 700,
      color: "#020B5A",
      align: "center",
      direction: "ltr",
      label: "Custom Text",
    },
  },
];

export const SAMPLE_STUDENT_PREVIEW_DATA = {
  student_name_en: "Mohamed Ghareeb Ibrahim",
  student_name_ar: "محمد غريب إبراهيم",
  program_name_en: "Professional Master of Business Administration",
  program_name_ar: "ماجستير إدارة الأعمال المهني",
  credential_number: "CAM-2026-000184",
  student_id_number: "STU-2026-000184",
  student_national_id: "298******14",
  student_country: "EGYPT",
  specialization: "Educational Psychology",
  degree_level: "Fellowship Program",
  grade: "Excellent",
  issue_date: "2026-01-15",
  expiry_date: "2031-01-15",
  college_name_en: "CAMBRIA INTERNATIONAL COLLEGE",
  college_name_ar: "كلية كامبريا الدولية",
  verification_url: "https://cambria-five.vercel.app/verify/tok_v8K29LpQx92M1a8B4z",
  verification_notice: "www.cambriainternational.com",
  qr_data_uri: "",
  student_avatar: "/images/avatar-placeholder.png",
};
